# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yotta2040.github.io" # the base hostname & protocol for your site 

# THEME-SPECIFIC CONFIGURATION
themesetting:
  # Meta
  title: Anthony Aguilar
  avatar: "https://avatars0.githubusercontent.com/u/33163875"
  gravatar: "https://s.gravatar.com/avatar/5b7d6cb3b5fa153de49d71c0f2f32dc3?s=80"
  description: "Coder , Blogger" # used by search engines

  # Header and footer text
  header_text: >
     <p> Hola, soy Anthony !</p>
     <p>Me gusta la tecnologia, la programacion, la musica, todo lo relacionado a la exploracion espacial, aprender nuevas cosa y enseñar a los demas!.</p>
  header_text_feature_image: "img/page/fondo_titulo.jpeg"
  footer_text: >
   Sigueme en twitter <a href="https://twitter.com/yotta2040">@yotta2040</a>

  # Icons
  rss: false
  email_address: "aguilaranthony.ve@gmail.com" #Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "yotta2040"
  google_plus:
  instagram:
  linkedin:  "https://ar.linkedin.com/in/aguilar-anthony-ve"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  
  steam:
  tumblr:
  twitter: "yotta2040"
  wordpress:
  youtube:

  # Scripts
  google_analytics: 
  disqus_shortname: "yotta2040-github-io"
  katex:  # Enable if using math markup

  # Localization strings
  str_follow_on: "Sigueme en"
  str_rss_follow: "Seguir la fuente RSS"
  str_email: "Email"
  str_next: "Siguiente"
  str_prev: "Anterior"
  str_continue_reading: "Continuar leyendo"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed


gems:
  - jekyll-feed
  - jekyll-sitemap
  
plugins:
  - jekyll-sitemap
